language: cpp
os: linux
dist: trusty
before_install:
  - sudo apt-get install python-dev
  - sudo apt-get install python3-dev
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python2 get-pip.py
  - sudo python3 get-pip.py
install:
  - pip2 install --user cffi
  - pip2 install --user numpy
  - pip3 install --user cffi
  - pip3 install --user numpy
  - pip3 install --user cython
script:
  - git clone https://github.com/UIUC-PPL/charm
  - cd charm
  - ./build charmpy netlrts-linux-x86_64 tcp -j2 --with-production --enable-error-checking > /dev/null
  - cd ..
  - cp charm/bin/charmrun charmrun
  - python3 setup.py `pwd`/charm --with-cython
  - python3 setup.py `pwd`/charm --with-cffi
  - python2 setup.py `pwd`/charm --with-cffi
  - export LD_LIBRARY_PATH=`pwd`/charm/lib
  - export PYTHONPATH=`pwd`
  - export CHARMPY_TEST_NUM_PROCESSES=2
  - python3 auto_test.py
