language: cpp
os: linux
dist: trusty
before_install:
  - sudo apt-get install python-dev
  - sudo apt-get install python3-dev
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python2 get-pip.py
  - sudo python3 get-pip.py
install:
  - pip2 install --user cffi
  - pip2 install --user numpy
  - pip3 install --user cffi
  - pip3 install --user numpy
  - pip3 install --user cython
script:
  - git clone https://github.com/UIUC-PPL/charm charm_src/charm
  - export CHARM_EXTRA_BUILD_OPTS="--enable-error-checking"
  - export CHARM_BUILD_PROCESSES=2
  - export CHARMPY_BUILD_CFFI=1
  - python3 setup.py build_ext --inplace
  - python2 setup.py build_ext --inplace
  - export PYTHONPATH=`pwd`
  - export CHARMPY_TEST_NUM_PROCESSES=2
  - python3 auto_test.py
