name: Charm4py

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
      - cron: '5 0 * * *'  # Runs at 00:05 UTC every day.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build-charm4py
      run: |
        git fetch --unshallow # Need full repo for 'git describe' used by setup.py
        pip3 install setuptools cython cffi greenlet numpy
        git clone https://github.com/UIUC-PPL/charm charm_src/charm
        export CHARM_EXTRA_BUILD_OPTS="--enable-error-checking"
        export CHARM_BUILD_PROCESSES=2
        export CHARM4PY_BUILD_CFFI=1
        python3 setup.py build_ext --inplace
    - name: test-charm4py
      run: |
        export PYTHONPATH="$PWD"
        export CHARM4PY_TEST_NUM_PROCESSES=2
        python3 auto_test.py
