name: debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build-charm4py
      run: |
        git fetch --unshallow # Need full repo for 'git describe' used by setup.py
        pip3 install setuptools cython greenlet numpy
        git clone https://github.com/UIUC-PPL/charm charm_src/charm
        export CHARM_EXTRA_BUILD_OPTS="--enable-error-checking"
        export CHARM_BUILD_PROCESSES=2
        python3 setup.py build_ext --inplace
        export CHARM4PY_TEST_NUM_PROCESSES=2
    - name: run-performance-comparsion
      run: |
        export PYTHONPATH="$PWD"
        git status
        git checkout -t origin/nightly-test
        git config --global user.email "simengl2@illinois.edu"
        git config --global user.name "Simeng Liu"
        git remote set-url origin https://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@github.com/slm960323/charm4py.git
        git status
        python3 -m charmrun.start +p2 tests/basics/pingpoing_with_nparray.py | tee .tmp/udp-cython-pingpong.log
        git add -A
        git commit -m "add .tmp/udp-cython-pingpong.log"
        git push origin nightly-test 
