name: debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build-charm4py
      run: |
        git fetch --unshallow # Need full repo for 'git describe' used by setup.py
        pip3 install setuptools cython cffi greenlet numpy
        git clone https://github.com/UIUC-PPL/charm charm_src/charm
        export CHARM_EXTRA_BUILD_OPTS="--enable-error-checking"
        export CHARM_BUILD_PROCESSES=2
        python3 setup.py build_ext --inplace
        export PYTHONPATH="$PWD"
    - name: run-performance-comparsion-cython
      run: |
        export PYTHONPATH="$PWD"
        git clone https://github.com/slm960323/task-bench.git
        cd task-bench
        pwd
        cd core
        make -j2
        export LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH
        cd ../../
        python3 task-bench/charm4py/task_bench.py
        
