name: debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build-charm4py
      run: |
        git fetch --unshallow # Need full repo for 'git describe' used by setup.py
        pip3 install setuptools cython cffi greenlet numpy
        git clone https://github.com/UIUC-PPL/charm charm_src/charm
        export CHARM_EXTRA_BUILD_OPTS="--enable-error-checking"
        export CHARM_BUILD_PROCESSES=2
        export CHARM4PY_BUILD_CFFI=1
        python3 setup.py build_ext --inplace
        export PYTHONPATH="$PWD"
        export CHARM4PY_TEST_NUM_PROCESSES=2
        pwd
        echo $HOME
        python3 -c "import sys;print(sys.path)"
        cd tests/basics
        python3 test.py
        python3 pingpoing_with_nparray.py
        python3 -m charmrun.start +p2 pingpoing_with_nparray.py
